### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by pikpokjeon** [ildang100/algorithm_java#1]

**Comment by lucky-jo** [comment]
> 실례합니다, 혹시 연락 주실 수 있으신가요?

https://open.kakao.com/o/sB29Hz1c

**Comment by pikpokjeon** [comment]
죄송합니다만 참여가 안되는 방입니다.

**Comment by pikpokjeon** [comment]
010 -2102 -1078 으로 문자하나 남겨주시겠어요? 감사합니다.
